/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista_Controlador;

import Modelo.*;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import java.util.Random;

/**
 *
 * @author l_mar
 */
public class Panel extends javax.swing.JFrame {

    //Inicializar el juego para contar los movimientos realizados
    Juego game = new Juego();
    
    //Crear una lista para guardar las fichas 
    public ArrayList<Ficha> list; 
    
    //Crear un vector para generar posiciones aleatorias para las fichas
    public int numeros[]= new int [15];
    
    //crear una funcion para llenar el vector de manera aleatoria sin repetir 
    public void llenarVectorAleatorio(){
        int n=15;
        int k=n;
        int[] resultado = new int[n];
        Random rnd = new Random();
        int res;
        
        for(int i=0; i<n; i++){
            this.numeros[i]=i;
        }
        
        for(int i=0; i<n; i++){
            res = rnd.nextInt(k);
            resultado[i] = this.numeros[res];
            this.numeros[res]=this.numeros[k-1];
            k--;
        }
        this.numeros = resultado;
    }
    
    /**
     * Creates new form Panel
     */
    public Panel() {
        initComponents();
        setLocationRelativeTo(null);
        btn16.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton(new ImageIcon ("1.png"));
        btn2 = new javax.swing.JButton(new ImageIcon("2.png"));
        btn3 = new javax.swing.JButton(new ImageIcon("3.png"));
        btn4 = new javax.swing.JButton(new ImageIcon("4.png"));
        btn5 = new javax.swing.JButton(new ImageIcon("5.png"));
        btn6 = new javax.swing.JButton(new ImageIcon("6.png"));
        btn7 = new javax.swing.JButton(new ImageIcon("7.png"));
        btn8 = new javax.swing.JButton(new ImageIcon("8.png"));
        btn9 = new javax.swing.JButton(new ImageIcon("9.png"));
        btn10 = new javax.swing.JButton(new ImageIcon("10.png"));
        btn11 = new javax.swing.JButton(new ImageIcon("11.png"));
        btn12 = new javax.swing.JButton(new ImageIcon("12.png"));
        btn13 = new javax.swing.JButton(new ImageIcon("13.png"));
        btn14 = new javax.swing.JButton(new ImageIcon("14.png"));
        btn15 = new javax.swing.JButton(new ImageIcon("15.png"));
        btn16 = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        Movimientos = new javax.swing.JLabel();
        Salir = new javax.swing.JButton();
        IniciarPartida = new javax.swing.JButton();
        NMovimientos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(700, 550));
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(395, 400));
        jPanel1.setMinimumSize(new java.awt.Dimension(395, 400));
        jPanel1.setLayout(new java.awt.GridLayout(4, 4));

        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn1);

        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn2);

        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel1.add(btn3);

        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel1.add(btn4);

        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel1.add(btn5);

        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel1.add(btn6);

        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel1.add(btn7);

        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel1.add(btn8);

        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel1.add(btn9);

        btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10ActionPerformed(evt);
            }
        });
        jPanel1.add(btn10);

        btn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn11ActionPerformed(evt);
            }
        });
        jPanel1.add(btn11);

        btn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn12ActionPerformed(evt);
            }
        });
        jPanel1.add(btn12);

        btn13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn13ActionPerformed(evt);
            }
        });
        jPanel1.add(btn13);

        btn14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn14ActionPerformed(evt);
            }
        });
        jPanel1.add(btn14);

        btn15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn15ActionPerformed(evt);
            }
        });
        jPanel1.add(btn15);

        btn16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn16ActionPerformed(evt);
            }
        });
        jPanel1.add(btn16);

        Titulo.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Puzzle");

        Movimientos.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        Movimientos.setText("Movimientos");

        Salir.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        IniciarPartida.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        IniciarPartida.setText("Nuevo Juego");
        IniciarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarPartidaActionPerformed(evt);
            }
        });

        NMovimientos.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        NMovimientos.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Movimientos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IniciarPartida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NMovimientos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Movimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NMovimientos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(IniciarPartida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Salir))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void IniciarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarPartidaActionPerformed
        IniciarPartida.setVisible(false);
        this.game.movimientos = 0;
        this.list = new ArrayList<Ficha>();
        
        for(int i=1; i<16; i++)
        {
            this.list.add(new Ficha(i));
        }
        
        llenarVectorAleatorio();
        btn1.setIcon(this.list.get(this.numeros[0]).getimg());btn2.setIcon(this.list.get(this.numeros[1]).getimg());btn3.setIcon(this.list.get(this.numeros[2]).getimg());
        btn4.setIcon(this.list.get(this.numeros[3]).getimg());btn5.setIcon(this.list.get(this.numeros[4]).getimg());btn6.setIcon(this.list.get(this.numeros[5]).getimg());
        btn7.setIcon(this.list.get(this.numeros[6]).getimg());btn8.setIcon(this.list.get(this.numeros[7]).getimg());btn9.setIcon(this.list.get(this.numeros[8]).getimg());
        btn10.setIcon(this.list.get(this.numeros[9]).getimg());btn11.setIcon(this.list.get(this.numeros[10]).getimg());btn12.setIcon(this.list.get(this.numeros[11]).getimg());
        btn13.setIcon(this.list.get(this.numeros[12]).getimg());btn14.setIcon(this.list.get(this.numeros[13]).getimg());btn15.setIcon(this.list.get(this.numeros[14]).getimg());
    }//GEN-LAST:event_IniciarPartidaActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        setVisible(false);
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        if(!btn2.isVisible()){
            this.game.movimientos++;
            NMovimientos.setText(Integer.toString(this.game.movimientos));
            btn1.setVisible(false);
            btn2.setVisible(true);
            btn2.setIcon(btn1.getIcon());
        }
        if(!btn5.isVisible()){
            this.game.movimientos++;
            NMovimientos.setText(Integer.toString(this.game.movimientos));
            btn1.setVisible(false);
            btn5.setVisible(true);
            btn5.setIcon(btn1.getIcon());
        }
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        if(!btn1.isVisible()){
            this.game.movimientos++;
            NMovimientos.setText(Integer.toString(this.game.movimientos));
            btn2.setVisible(false);
            btn1.setVisible(true);
            btn1.setIcon(btn2.getIcon());
        }
        if(!btn3.isVisible()){
            this.game.movimientos++;
            NMovimientos.setText(Integer.toString(this.game.movimientos));
            btn2.setVisible(false);
            btn3.setVisible(true);
            btn3.setIcon(btn2.getIcon());
        }
        if(!btn6.isVisible()){
            this.game.movimientos++;
            NMovimientos.setText(Integer.toString(this.game.movimientos));
            btn2.setVisible(false);
            btn6.setVisible(true);
            btn6.setIcon(btn2.getIcon());
        }
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        if(!btn2.isVisible()){
            this.game.movimientos++;
            NMovimientos.setText(Integer.toString(this.game.movimientos));
            btn3.setVisible(false);
            btn2.setVisible(true);
            btn2.setIcon(btn3.getIcon());
        }
        if(!btn4.isVisible()){
            this.game.movimientos++;
            NMovimientos.setText(Integer.toString(this.game.movimientos));
            btn3.setVisible(false);
            btn4.setVisible(true);
            btn4.setIcon(btn3.getIcon());
        }
        if(!btn7.isVisible()){
            this.game.movimientos++;
            NMovimientos.setText(Integer.toString(this.game.movimientos));
            btn3.setVisible(false);
            btn7.setVisible(true);
            btn7.setIcon(btn3.getIcon());
        }
    }
    
    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        if(!btn3.isVisible()){
            this.game.movimientos++;
            NMovimientos.setText(Integer.toString(this.game.movimientos));
            btn4.setVisible(false);
            btn3.setVisible(true);
            btn3.setIcon(btn4.getIcon());
        }
        if(!btn8.isVisible()){
            this.game.movimientos++;
            NMovimientos.setText(Integer.toString(this.game.movimientos));
            btn4.setVisible(false);
            btn8.setVisible(true);
            btn8.setIcon(btn4.getIcon());
        }
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        if(!btn1.isVisible()){
            this.game.movimientos++;
            NMovimientos.setText(Integer.toString(this.game.movimientos));
            btn5.setVisible(false);
            btn1.setVisible(true);
            btn1.setIcon(btn5.getIcon());
        }
        if(!btn6.isVisible()){
            this.game.movimientos++;
            NMovimientos.setText(Integer.toString(this.game.movimientos));
            btn5.setVisible(false);
            btn6.setVisible(true);
            btn6.setIcon(btn5.getIcon());
        }
        if(!btn9.isVisible()){
            this.game.movimientos++;
            NMovimientos.setText(Integer.toString(this.game.movimientos));
            btn5.setVisible(false);
            btn9.setVisible(true);
            btn9.setIcon(btn5.getIcon());
        }
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        if(!btn2.isVisible()){
            this.game.movimientos++;
            NMovimientos.setText(Integer.toString(this.game.movimientos));
            btn6.setVisible(false);
            btn2.setVisible(true);
            btn2.setIcon(btn6.getIcon());
        }
        if(!btn5.isVisible()){
            this.game.movimientos++;
            NMovimientos.setText(Integer.toString(this.game.movimientos));
            btn6.setVisible(false);
            btn5.setVisible(true);
            btn5.setIcon(btn6.getIcon());
        }
        if(!btn7.isVisible()){
            this.game.movimientos++;
            NMovimientos.setText(Integer.toString(this.game.movimientos));
            btn6.setVisible(false);
            btn7.setVisible(true);
            btn7.setIcon(btn6.getIcon());
        }
        if(!btn10.isVisible()){
            this.game.movimientos++;
            NMovimientos.setText(Integer.toString(this.game.movimientos));
            btn6.setVisible(false);
            btn10.setVisible(true);
            btn10.setIcon(btn6.getIcon());
        }
    }
    
    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        if(!btn3.isVisible()){
            this.game.movimientos++;
            NMovimientos.setText(Integer.toString(this.game.movimientos));
            btn7.setVisible(false);
            btn3.setVisible(true);
            btn3.setIcon(btn7.getIcon());
        }
        if(!btn6.isVisible()){
            this.game.movimientos++;
            NMovimientos.setText(Integer.toString(this.game.movimientos));
            btn7.setVisible(false);
            btn6.setVisible(true);
            btn6.setIcon(btn7.getIcon());
        }
        if(!btn8.isVisible()){
            this.game.movimientos++;
            NMovimientos.setText(Integer.toString(this.game.movimientos));
            btn7.setVisible(false);
            btn8.setVisible(true);
            btn8.setIcon(btn7.getIcon());
        }
        if(!btn11.isVisible()){
            this.game.movimientos++;
            NMovimientos.setText(Integer.toString(this.game.movimientos));
            btn7.setVisible(false);
            btn11.setVisible(true);
            btn11.setIcon(btn7.getIcon());
        }
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        if(!btn4.isVisible()){
            this.game.movimientos++;
            NMovimientos.setText(Integer.toString(this.game.movimientos));
            btn8.setVisible(false);
            btn4.setVisible(true);
            btn4.setIcon(btn8.getIcon());
        }
        if(!btn7.isVisible()){
            this.game.movimientos++;
            NMovimientos.setText(Integer.toString(this.game.movimientos));
            btn8.setVisible(false);
            btn7.setVisible(true);
            btn7.setIcon(btn8.getIcon());
        }
        if(!btn12.isVisible()){
            this.game.movimientos++;
            NMovimientos.setText(Integer.toString(this.game.movimientos));
            btn8.setVisible(false);
            btn12.setVisible(true);
            btn12.setIcon(btn8.getIcon());
        }
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        if(!btn5.isVisible()){
            this.game.movimientos++;
            NMovimientos.setText(Integer.toString(this.game.movimientos));
            btn9.setVisible(false);
            btn5.setVisible(true);
            btn5.setIcon(btn9.getIcon());
        }
        if(!btn10.isVisible()){
            this.game.movimientos++;
            NMovimientos.setText(Integer.toString(this.game.movimientos));
            btn9.setVisible(false);
            btn10.setVisible(true);
            btn10.setIcon(btn9.getIcon());
        }
        if(!btn13.isVisible()){
            this.game.movimientos++;
            NMovimientos.setText(Integer.toString(this.game.movimientos));
            btn9.setVisible(false);
            btn13.setVisible(true);
            btn13.setIcon(btn9.getIcon());
        }
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10ActionPerformed
        if(!btn6.isVisible()){
            this.game.movimientos++;
            NMovimientos.setText(Integer.toString(this.game.movimientos));
            btn10.setVisible(false);
            btn6.setVisible(true);
            btn6.setIcon(btn10.getIcon());
        }
        if(!btn9.isVisible()){
            this.game.movimientos++;
            NMovimientos.setText(Integer.toString(this.game.movimientos));
            btn10.setVisible(false);
            btn9.setVisible(true);
            btn9.setIcon(btn10.getIcon());
        }
        if(!btn11.isVisible()){
            this.game.movimientos++;
            NMovimientos.setText(Integer.toString(this.game.movimientos));
            btn10.setVisible(false);
            btn11.setVisible(true);
            btn11.setIcon(btn10.getIcon());
        }
        if(!btn14.isVisible()){
            this.game.movimientos++;
            NMovimientos.setText(Integer.toString(this.game.movimientos));
            btn10.setVisible(false);
            btn14.setVisible(true);
            btn14.setIcon(btn10.getIcon());
        }
    }//GEN-LAST:event_btn10ActionPerformed

    private void btn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn11ActionPerformed
        if(!btn7.isVisible()){
            this.game.movimientos++;
            NMovimientos.setText(Integer.toString(this.game.movimientos));
            btn11.setVisible(false);
            btn7.setVisible(true);
            btn7.setIcon(btn11.getIcon());
        }
        if(!btn10.isVisible()){
            this.game.movimientos++;
            NMovimientos.setText(Integer.toString(this.game.movimientos));
            btn11.setVisible(false);
            btn10.setVisible(true);
            btn10.setIcon(btn11.getIcon());
        }
        if(!btn12.isVisible()){
            this.game.movimientos++;
            NMovimientos.setText(Integer.toString(this.game.movimientos));
            btn11.setVisible(false);
            btn12.setVisible(true);
            btn12.setIcon(btn11.getIcon());
        }
        if(!btn15.isVisible()){
            this.game.movimientos++;
            NMovimientos.setText(Integer.toString(this.game.movimientos));
            btn11.setVisible(false);
            btn15.setVisible(true);
            btn15.setIcon(btn11.getIcon());
        }
    }//GEN-LAST:event_btn11ActionPerformed

    private void btn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn12ActionPerformed
        if(!btn8.isVisible()){
            this.game.movimientos++;
            NMovimientos.setText(Integer.toString(this.game.movimientos));
            btn12.setVisible(false);
            btn8.setVisible(true);
            btn8.setIcon(btn12.getIcon());
        }
        if(!btn11.isVisible()){
            this.game.movimientos++;
            NMovimientos.setText(Integer.toString(this.game.movimientos));
            btn12.setVisible(false);
            btn11.setVisible(true);
            btn11.setIcon(btn12.getIcon());
        }
        if(!btn16.isVisible()){
            this.game.movimientos++;
            NMovimientos.setText(Integer.toString(this.game.movimientos));
            btn12.setVisible(false);
            btn16.setVisible(true);
            btn16.setIcon(btn12.getIcon());
        }
    }//GEN-LAST:event_btn12ActionPerformed

    private void btn13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn13ActionPerformed
        if(!btn9.isVisible()){
            this.game.movimientos++;
            NMovimientos.setText(Integer.toString(this.game.movimientos));
            btn13.setVisible(false);
            btn9.setVisible(true);
            btn9.setIcon(btn13.getIcon());
        }
        if(!btn14.isVisible()){
            this.game.movimientos++;
            NMovimientos.setText(Integer.toString(this.game.movimientos));
            btn13.setVisible(false);
            btn14.setVisible(true);
            btn14.setIcon(btn13.getIcon());
        }
    }//GEN-LAST:event_btn13ActionPerformed

    private void btn14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn14ActionPerformed
        if(!btn10.isVisible()){
            this.game.movimientos++;
            NMovimientos.setText(Integer.toString(this.game.movimientos));
            btn14.setVisible(false);
            btn10.setVisible(true);
            btn10.setIcon(btn14.getIcon());
        }
        if(!btn13.isVisible()){
            this.game.movimientos++;
            NMovimientos.setText(Integer.toString(this.game.movimientos));
            btn14.setVisible(false);
            btn13.setVisible(true);
            btn13.setIcon(btn14.getIcon());
        }
        if(!btn15.isVisible()){
            this.game.movimientos++;
            NMovimientos.setText(Integer.toString(this.game.movimientos));
            btn14.setVisible(false);
            btn15.setVisible(true);
            btn15.setIcon(btn14.getIcon());
        }
    }//GEN-LAST:event_btn14ActionPerformed

    private void btn15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn15ActionPerformed
        if(!btn11.isVisible()){
            this.game.movimientos++;
            NMovimientos.setText(Integer.toString(this.game.movimientos));
            btn15.setVisible(false);
            btn11.setVisible(true);
            btn11.setIcon(btn15.getIcon());
        }
        if(!btn14.isVisible()){
            this.game.movimientos++;
            NMovimientos.setText(Integer.toString(this.game.movimientos));
            btn15.setVisible(false);
            btn14.setVisible(true);
            btn14.setIcon(btn15.getIcon());
        }
        if(!btn16.isVisible()){
            this.game.movimientos++;
            NMovimientos.setText(Integer.toString(this.game.movimientos));
            btn15.setVisible(false);
            btn16.setVisible(true);
            btn16.setIcon(btn15.getIcon());
        }
    }//GEN-LAST:event_btn15ActionPerformed

    private void btn16ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        if(!btn12.isVisible()){
            this.game.movimientos++;
            NMovimientos.setText(Integer.toString(this.game.movimientos));
            btn16.setVisible(false);
            btn12.setVisible(true);
            btn12.setIcon(btn16.getIcon());
        }
        if(!btn15.isVisible()){
            this.game.movimientos++;
            NMovimientos.setText(Integer.toString(this.game.movimientos));
            btn16.setVisible(false);
            btn15.setVisible(true);
            btn15.setIcon(btn16.getIcon());
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IniciarPartida;
    private javax.swing.JLabel Movimientos;
    private javax.swing.JLabel NMovimientos;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn13;
    private javax.swing.JButton btn14;
    private javax.swing.JButton btn15;
    private javax.swing.JButton btn16;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
